tupla = ('', 'Palmeiras', 'Grêmio', 'Atlético-MG', 'Flamengo', 'Botafogo', 'Bragantino', 'Fluminense', 'Athletico-PR', 'Internacional', 'Fortaleza', 'São Paulo', 'Cuiabá', 'Corinthians', 'Cruzeiro', 'Vasco', 'Bahia', 'Santos', 'Goiás', 'Coritiba', 'América-MG')
print('-=' * 20)
print(f'Lista de times do Brasileirão: {tupla[1:]}')
print('-=' * 20)
print(f'Os 5 primeiros são {tupla[1:6]}')
print('-=' * 20)
print(f'Os 4 últimos são {tupla[-4:]}')
print('-=' * 20)
print(f'Times em ordem alfabética: {sorted(tupla[1:])}')
print('-=' * 20)
print(f'O {tupla[8]} esta na {tupla.index("Athletico-PR")}ª posição.')